project:
  type: website
  output-dir: docs

website:
  title: "Kennedy-Kioko"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        href: "https://github.com/FarmerKE"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

